# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Prashant Jadhav
tagline:             ''
description:         ''
url:                 http://www.prashantjadhav.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:
  url:
  email:

# Custom vars
version:             1.0.0
theme : lanyon
