--- 
- 
  connection: local
  hosts: localhost
  name: "Terminate bastion instance"
  tasks: 
    - 
      ec2: 
        aws_access_key: "{{ aws_access_key}}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_ids: "{{ instance_ids }}"
        region: ap-south-1
        state: absent
      name: "Terminate bastion instance that was previously launched"
