--- 
- 
  connection: local
  hosts: localhost
  name: "Terminate instances"
  tasks: 
    - 
      ec2: 
        aws_access_key: AKIAJPMNIMEPTRBGXHEA
        aws_secret_key: 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
        instance_ids: i-094c554f8a0009dee
        region: us-east-1
        state: absent
      name: "Terminate instances that were previously launched"
